// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FinancesController from "./finances/finances_controller"
import AccountSavedController from "./finances/account_saved_controller"

application.register("finances", FinancesController)
application.register("finances--account-saved", AccountSavedController)