services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: bdgtr
      POSTGRES_PASSWORD: localdev
    ports:
      - "5432:5432"
#    volumes:
#      - bdgtr-db:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: always

volumes:
  bdgtr-db:
  bdgtr-redis: